---
title: "Untitled"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

```{r message=FALSE}
library(tidyverse)
library(readxl)
library(haven)
theme_set(theme_light())

wgi <- read_dta("wgidataset_stata/wgidataset.dta")
polity <- read_excel("p4v2017.xls") %>% rename(countryname = country)

```

```{r}
wgi_polity <- wgi %>% inner_join(polity, by = c("countryname", "year")) 
china <- wgi_polity %>% filter(year == 2017, countryname == "China") 

wgi_polity %>% 
  select(year, vae, pve, gee, rqe, rle, cce, polity2) %>% 
  gather(metric, value, -year, -polity2) %>% 
  mutate(regime = ifelse(polity2 > 5, "democracy", "autocrary")) %>% 
  filter(year == 2017) %>% 
  ggplot(aes(polity2, value, color = regime)) +
  geom_point() + 
  geom_smooth(method = "lm", se = FALSE) +
  facet_wrap(~ metric)

```

## Government effectiveness

```{r}
library(ggrepel)

wgi_polity %>% 
  filter(year == 2017) %>% 
  mutate(regime = ifelse(polity2 > 5, "democracy", "autocrary")) %>% 
  ggplot(aes(polity2, gee)) + 
  geom_point() +
  geom_smooth(method = "lm", se = FALSE) +
  geom_label_repel(data = china, aes(polity2, gee, label = countryname), 
                   box.padding   = 0.35, 
                   point.padding = 0.5,
                   segment.color = 'grey50') +
  labs(x = "POLITY IV", 
       y = "Government effectiveness")
```

## Rule of law 

```{r}
wgi_polity %>% 
  filter(year == 2017) %>% 
  mutate(regime = ifelse(polity2 > 5, "democracy", "autocrary")) %>% 
  ggplot(aes(polity2, rle)) + 
  geom_point() +
  geom_smooth(method = "lm", se = FALSE) +
  geom_label_repel(data = china, aes(polity2, rle, label = countryname), 
                   box.padding   = 0.35, 
                   point.padding = 0.5,
                   segment.color = 'grey50') + 
  labs(x = "POLITY IV", 
       y = "Rule of law")
```

## Voice and accountability 

```{r}
wgi_polity %>% 
  filter(year == 2017) %>% 
  mutate(regime = ifelse(polity2 > 5, "democracy", "autocrary")) %>% 
  ggplot(aes(polity2, vae)) + 
  geom_point() +
  geom_smooth(method = "lm", se = FALSE) +
  geom_label_repel(data = china, aes(polity2, vae, label = countryname), 
                   box.padding   = 0.35, 
                   point.padding = 0.5,
                   segment.color = 'grey50') +
  labs(x = "POLITY IV", 
       y = "Voice and accountability")
```

## Political stability and absence of violence

```{r}
wgi_polity %>% 
  filter(year == 2017) %>% 
  mutate(regime = ifelse(polity2 > 5, "democracy", "autocrary")) %>% 
  ggplot(aes(polity2, pve)) + 
  geom_point() +
  geom_smooth(method = "lm", se = FALSE) +
  geom_label_repel(data = china, aes(polity2, pve, label = countryname), 
                   box.padding   = 0.35, 
                   point.padding = 0.5,
                   segment.color = 'grey50') + 
  labs(x = "POLITY IV", 
       y = "Political stability")
```

## Regulatory quality

```{r}
wgi_polity %>% 
  filter(year == 2017) %>% 
  mutate(regime = ifelse(polity2 > 5, "democracy", "autocrary")) %>% 
  ggplot(aes(polity2, rqe)) + 
  geom_point() +
  geom_smooth(method = "lm", se = FALSE) +
  geom_label_repel(data = china, aes(polity2, rqe, label = countryname), 
                   box.padding   = 0.35, 
                   point.padding = 0.5,
                   segment.color = 'grey50') +
  labs(x = "POLITY IV", 
       y = "Regulatory quality")
```

## Control of corruption

```{r}
wgi_polity %>% 
  filter(year == 2017) %>% 
  mutate(regime = ifelse(polity2 > 5, "democracy", "autocrary")) %>% 
  ggplot(aes(polity2, cce)) + 
  geom_point() +
  geom_smooth(method = "lm", se = FALSE) +
  geom_label_repel(data = china, aes(polity2, cce, label = countryname), 
                   box.padding   = 0.35, 
                   point.padding = 0.5,
                   segment.color = 'grey50') + 
  labs(x = "POLITY IV", 
       y = "Corruption control")
```

